version: '3.7'

services:

  app:
    image: 'test-task-tribe'
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    networks:
      - prometheus_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - prometheus_net

networks:
  prometheus_net:
    driver: bridge

